name: (Reusable) Setup Environments Matrix

on:
  workflow_call:
    inputs:
      environment:
        description: "Single environment to run (if empty, runs all environments)"
        required: false
        type: string
    outputs:
      environments:
        description: "JSON array of environments to process"
        value: ${{ jobs.setup.outputs.environments }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - name: Set environments matrix
        id: set-environments
        run: |
          if [ -z "${{ inputs.environment }}" ]; then
            environments_json='["wc2-live", "wc2-approval", "wc2-tuidemo", "odp-live", "odp-approval", "odp-tui-demo"]'
            echo "environments=$environments_json" >> $GITHUB_OUTPUT
            echo "Running for all environments: $environments_json"
          else
            # Specific environment provided
            echo "environments=[\"${{ inputs.environment }}\"]" >> $GITHUB_OUTPUT
            echo "Running for specific environment: ${{ inputs.environment }}"
          fi
