name: Certificate Checks
on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: false
        type: environment

jobs:
  setup:
    name: Setup Environments Matrix
    uses: ./.github/workflows/_setup-environments.yml
    with:
      environment: ${{ inputs.environment }}

  debug:
    name: Debug matrix
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
          echo ${{ needs.setup.outputs.environments }}

  execute-gauge:
    name: ${{ matrix.environment }}
    needs: setup
    uses: ./.github/workflows/_execute-gauge.yml
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.environments) }}
    secrets: inherit
    with:
      displayName: "Certificate Checks"
      environment: ${{ matrix.environment }}
      gaugeParams: "--parallel -n=8"
      gaugeSpecs: "specs/platform-core/service/"
      gaugeTags: "certificate-check"

